### ISSUE TITLE
Assessment List

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#1]
## Value proposition
- As a User
- I want to be able to see a list of all assessments with a brief detail overview, especially the result
- so I have a quick overview about all my assessments and their level of criticality

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/61ede195-6b19-45e3-a27e-1dc8e6e59d00)

## Acceptance criteria
- [ ] there is a list of assessments, each item 
  includes following details: 
    - [ ] there is a specific assessment title  
    - [ ] editor is displayed 
    - [ ] result is displayed 
- [ ] assessment list is vertically scrollable
- [ ] error message if data can't be displayed
- [ ] app title displayed

## Tasks
- [ ] create feature branch "assessment list"
- [ ] create example data
- [ ] create card components which contains card
    - [ ] map over example data 
- [ ] render Cards in Index.js
- [ ] create Header with app-title
