### ISSUE TITLE
Add DB Functionality - Read

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#13]
## Value proposition
- As a User
- I want to be able to see the assessments from the DB
- so that I can take a look at the persistent information every time I need to 

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/48dc39a9-f92c-4a5d-9788-dc2bf25fffc1)

## Acceptance criteria
- [ ] Data respectively assessments are persistent

## Tasks
- [ ] Create DB-Folder
- [ ] Create Assessments.js in DB Folder an write Schema
- [ ] Install Dependency mongoose 
- [ ] in db folder create connect.js and copy paste the content 
- [ ] Create Backend Folders 
   - [ ] Api -> assessments
       - [ ] index.js. -> GET and POST Requests 
       - [ ] [id].js -> for specific assessments GET, PUT and DELETE Requests
- [ ] in Backend index.js write function for GET Request 
- [ ] go to MongoDB Atlas and create DB with corresponding collection
- [ ] create .env.local file and hand over key
- [ ] install SWR dependency and add import to AssessmentList.js
- [ ] in AssessmenList.js start fetching data from DB using the SWR-Hook.
- [ ] make sure to name the data-object which is received from the hook properly (data: assessments) so that the map and color-coding functionality works as before
