### ISSUE TITLE
Add DB Functionality - Create/Edit

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#14]
## Value proposition
- As a User
- I want to be able to add and edit my own assessments to the DB
- so that I can create and edit persistent Assessments every time I need to 

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/5ff01937-9a60-428c-bee3-9c805577b2cb)

## Acceptance criteria
- [ ] Created assessments are persistent
- [ ] Changes are persistent
- [ ] Functionality is the same as before (expect search-function)

## Tasks
- [ ] In Backend add methods for Post in index.js 
- [ ] In Backend [id] add method for GET, PUT 
- [ ] Create folder structure for detailPage and edit assessments -> assessments -> [id] -> index.js / edit.js
- [ ] In index.js fetch specific assessment an render detailPage as before
- [ ] in edit.js fetch specific assessment and handle it to form.js. Also write editAssessment-Function which updates db (PUT method) with the new data and pass it to form.js. Render form-component in return-expression. Don´t forget mutate-function if update is successful. 
- [ ] delete form folder in pages
- [ ] create create.js and write newAssessment function which updates db (POST method) with the new data and pass it to form.js. Don't forget mutate-function if response is ok. Render form component in return expression. 
- [ ] Move Edit  Button from AssessmentList component to Detail Page 
- [ ] Delete functions and states form app.js that are no longer needed

**Comment by ThomasKirst** [comment]
Very detailed US, great attention to details, also good to consider clean-up tasks.

Normally I would say that the US is too big, but since you have already prepared the form well, replacing the implementation shouldn't be too much of a hassle.
