### ISSUE TITLE
Add DB Functionality - Delete

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#15]
## Value proposition
- As a User
- I want to be able to  delete my own assessments from the DB
- so that I can delete persistent Assessments that I don't need anymore.

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/5ff01937-9a60-428c-bee3-9c805577b2cb)

## Acceptance criteria
- [ ] Deleting is persistent 
- [ ] Functionality is the same as before 

## Tasks
- [ ] In Backend [id] add method fo DELETE
- [ ] Move Delete Button from AssessmentList component to Detail Page 
- [ ] in index.js (new DetailPage) write function for deleting assessment (DELETE Method)
- [ ] Delete functions and states form app.js that are no longer needed
