### ISSUE TITLE
Update Search Assessment Functionality 

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#19]
## Value proposition
- As a User
- I want to be able to search for specific assessments
- so that I can find specific assessments easily and look at the result.

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/35793ff1-fc9e-4d0f-b040-331ad48759de)

## Acceptance criteria
- [ ] Search functionality is located on top of the hompepage. 
- [ ]  Consisting of:
    - [ ]  an input field for the assessment title and a corresponding label of the input field
    - [ ] a "search"-button
    - [ ] a "back to overview"-button
- [ ] When the "search" button is clicked, only the assessments with the title that corresponds to or is contained in the searched title are displayed
- [ ] The search is not case sensitive
- [ ] By clicking the "back to overview" button, all assessments are displayed again

## Tasks
- [ ] Move state and functions around search functionality from _app.js in index.js
- [ ] Move Filter-Function in AssessmentList.js
- [ ] From index.js pass searchTerm to AssessmentList.js
- [ ] Pass function to set the searchTerm and function to reset searchTerm to SearchAssessment.js
