### ISSUE TITLE
Create Assessment 

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#2]
## Value proposition
- As a User
- I want to be able to add my own assessments
- so I can so that I am able to receive a specific evaluation of my planned AI project

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/98e9a59a-1a11-4666-bccb-b53990617979)

## Acceptance criteria
- [ ] there is a  "new assessment"-button on the homepage
- [ ]  the "new assessment"-button opens a form
- [ ] the form includes the following details: 
    - [ ] 4 input fields  -> title of the AI, name of the processor, name of the company and the processing status 
    - [ ] Checkboxes that query the essential parameters according to the AI Regulation for the classification of AI systems
- [ ] "Submit" button, which converts the entered data into a new assessment. 
- [ ] The "Submit" button redirects the user to the homepage. 
- [ ] The new assessment is displayed as a card section on the homepage. 

## Tasks
- [ ] create feature branch "create-assessment"
- [ ] create form component in components-folder with the corresponding input-fields and checkboxes
- [ ] create "input"-state in the form component, so that the input fields can be controlled input-fields. On the one hand, this is important so that the key-value-pairs of the corresponding assessment object receive the boolean values false and true depending on the setting of the checkbox and so that the edit functionality for the checkboxes works correctly in a later step.
- [ ]  write the handleInputChange-function which updates the state as soon as an entry is made in one of the input fields
- [ ] in form component write handleSubmit-function which passes an object containing the input data to a function in the index.js
- [ ] create form-folder which displays form-component
- [ ] in app.js create state, which handles all assessments
- [ ] Write handleNewAssessment-function that catches the newly created object with the input data in the form component and updates the assessment state. Make sure to add an id.
- [ ] pass handleNewAssessment-function to the form-component 
- [ ] pass the "assessment"-state to the AssessmentList-component  
- [ ] now use map-function in card-component to map over the "assessment"-state an create the specific card-components

**Comment by F-Kirchhoff** [comment]
Hey Julian,
great user story so far. I only have minor issues with the naming some elements and a suggestion about handling the form:
- please call the branch "create-assessment" or "assessment-form"
- You are mixing up some naming with the "Card" component. It seems as if you want to map over the assessement array in this "Card" component. But that would be a list of cards then. Another dev would look at the name and interpret the component as "a single card" instead of a mapped list of cards. So either you rename the component to "AssessmentList" or you move the Mapping of the "AssessmentCards" into the index.js and create a "Card" for each element in the array.
- If specify that you plan to create controlled inputs for the assessment form. But unless you want to use any input values dynamically inside the form, it would be much easier to just use the "onSubmit" event and collect all form data with the "new FormData(event.target)" approach that you learned. Maybe you want to change that in your tasks.

Thats all for now 🥳

**Comment by JulianKle** [comment]
Hi Felix, thank you very much for your input. I have made the adjustments so far. For the input fields, I have added an explanation of why a state should be used. I have already tried a bit here and especially pre-filling the formluar field with existing data and updating clicked checkboxes to unchecked ones was a problem without controlled input fields. Or am I missing something at this point?

**Comment by F-Kirchhoff** [comment]
Hey Julian,
there is a way to work with checkboxes and FormData, but its a bit different to the other inputs: https://stackoverflow.com/questions/33487360/formdata-and-checkboxes. Of course, you can decide which way to go, just that you know all alternatives.

**Comment by F-Kirchhoff** [comment]
And you need to update the "Card Component" name to "AssessmentList" in your last task as well. Please update your first user story as well, where you named the component "Card" too.
