### ISSUE TITLE
Edit Assessment

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#3]
## Value proposition
- As a User
- I want to be able to edit my own assessments
- so that I can correct errors in the input or take into account changes in the functionality of the AI system in my already created assessment

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/62ddf641-ecca-41fa-b3dc-7b08cd36ee25)

## Acceptance criteria
- [ ] There is a  "edit"-button displayed on each card
- [ ]  The "edit"-button opens the form component with the pre filled data from the specific assessment
- [ ] Specific Heading: Edit "Assessment Titel" 
- [ ] It is possible to adjust only the changed data. The remaining data can remain untouched.
- [ ] The "Submit" button redirects the user to the homepage. 
- [ ] The edited Assessment is displayed with the changed data on the homepage as card. 

## Tasks
- [ ] Create feature branch "edit-assessment"
- [ ] Create "edit"-button in AssessmentList compononent
- [ ] "Edit"-button is a Link to the index.js in the form folder
- [ ] onClick of the "edit"-button calls the onEditAssessment-function (handleEditAssessment-function in the app.js) which is passed as an argument the specific id of the assessment which is about to be changed 
- [ ] Create the state "editingAssessment", which will be filled with the specific object to be changed. Initialize it with "null".
- [ ] In app.js create function handleEditAssessment (which is being passed to the assessmentList.js under the name onEditAssessment). This function uses the supplied id to find the object to be changed and sets the editAssessment state to this object 
- [ ] Ensure that the editAssessment state is passed to the index.js of the form folder and, if required, also to the form component. For this purpose, conditional JSX is written so that the editAssessment state is only passed to the form component if it is not null. At this point, depending on whether editAssessment is null or not, either the handleNewAssessment or handleUpdateAssessment function is passed to the form component. One of these functions is then accessed in the form component in the onSubmit function.
- [ ] In the form component, change the state so that it either uses the data from editAssessment or remains empty if it is not available. 
- [ ] In App.js write the handleUpdateAssessment-function. This function then updates the specific assessment object from the assessment state with the new data and resets the editingAssessment state to zero.
