### ISSUE TITLE
Delete Assessment

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#4]
## Value proposition
- As a User
- I want to be able to delete assessments
- so that I can delete assessments that I do not need anymore

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/3dc7e883-98c2-49c2-870f-0c78b20a08de)

## Acceptance criteria
- [ ] There is a  "delete"-button displayed on each card
- [ ]  The "delete"-button causes the respective card to be deleted.
- [ ] The remaining overview of the assessments is retained

## Tasks
- [ ] Create feature branch "delete-assessment"
- [ ] Create "delete"-button in AssessmentList compononent
- [ ] onClick of the "delete"-button calls the onDeleteAssessment-function (handleDeleteAssessment-function in the app.js) which is passed as an argument the specific id of the assessment which is about to be deleted
- [ ] In app.js create function handleDeleteAssessment (which is being passed to the assessmentList.js under the name onDeleteAssessment). This function uses the supplied as id as an argument to find the object to be deleted and changes the "assessment" state accordingly
