### ISSUE TITLE
Search for Assessments 

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#5]
## Value proposition
- As a User
- I want to be able to search for specific assessments
- so that I can find specific assessments easily and look at the result.

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/35793ff1-fc9e-4d0f-b040-331ad48759de)

## Acceptance criteria
- [ ] Search functionality is located on top of the hompepage. 
- [ ]  Consisting of:
    - [ ]  an input field for the assessment title and a corresponding label of the input field
    - [ ] a "search"-button
    - [ ] a "back to overview"-button
- [ ] When the "search" button is clicked, only the assessments with the title that corresponds to or is contained in the searched title are displayed
- [ ] The search is not case sensitive
- [ ] By clicking the "back to overview" button, all assessments are displayed again

## Tasks
- [ ] Create feature branch "searchFunctionality"
- [ ] Create searchAssessment component
- [ ] SearchAssessment component is a form field with an input field and two buttons
- [ ] The search button is type "submit". onClick calls the onSearch function (called noFilterFalse function in the app.js). 
- [ ] The "back to overview" button is of type "reset" and calls onClick the onOverview function (noFilzerTrue function in the app.js) 
- [ ] onSubmit calls the filterName function, which is located in the SearchAssessment component and passes the value of the input field as an argument to the onFilter (filterAssessment function in the app.js).
- [ ]  Two new states are initiated in the App.js: 
    - [ ] the "filteredAssessment" state, which is filled with the respective objects being searched for
    - [ ]  "filterNoYes" state, which is used to either pass in the entire array of objects from the Assessment state or only the filtered                objects from the filteredAssessment state using conditional JSX in the index.js of the AssessmentList component.
- [ ] The filterAssessment function must be written in App.js, which takes the value of the input field as an argument. Within the function, the filteredAssessment state is set to the object or objects that have the same title as the searched title.
- [ ] The noFilterFalse or noFilterTrue function sets the filterNoYes state to true/false, so that either all assessments or only the filtered ones are displayed -> see the section on conditional JSX
