### ISSUE TITLE
Detail Page 

### ISSUE THREAD

**Issue by JulianKle** [JulianKle/capstone-project#6]
## Value proposition
- As a User
- I want to be able to see details for my specific assessment/s
- so that I can view further information on the obligations resulting from the result of the classification of my AI system.

## Description
![image](https://github.com/JulianKle/capstone-project/assets/148042845/a3c04dd4-d882-417a-a179-15c2ad88f25c)

## Acceptance criteria
- [ ] There is a  "Detail"-button displayed on each card
- [ ]  The "Detail"-button links to the specific detail page
- [ ] Specific Heading: Detail Page for: "Assessment Titel" 
- [ ] "Back to homepage"-button which leads to the homepage with all assessments

## Tasks
- [ ] Create DetailPage-Folder
- [ ] create [id].js file in DetailPage folder -> Implement dynamic routing 
- [ ] Assessments State is passed to the DetailPage.
- [ ] Id is read from router.query. Assessments are filtered by id in order to find the object being searched for.  The filtered object is stored into the variable detailAssessment.
- [ ] Based on the risk assessment (logic for this can be taken from the AssessmenList component), the highlights of the respective obligations and transparency obligations under the AI Regulation are displayed.  
- [ ] "Back to homepage"-button is a Link to the homepage

**Comment by JessicaLoers** [comment]
**Hi @JulianKle**  ✌️
your User Story is well-structured, the value proposition is clear, highlighting the need for users and the AC cover the essential functionalities.
